services:
  localhost:
    image: alpine:latest
    command: sleep infinity
    ports:
      - "8080:8080" # Keycloak port
      - "8989:8989" # Application port
      - "5005:5005" # Application debug port
  app:
    image: "app:0.0.1"
    container_name: "app"
    build:
      context: .
    depends_on:
      mysqldb:
        condition: service_healthy
      keycloak:
        condition: service_started
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/mysql-db?createDatabaseIfNotExist=true"
      SPRING_DATASOURCE_USERNAME: "appuser"
      SPRING_DATASOURCE_PASSWORD: "appuser@123"
      JWT_ISSUER_URI: "http://localhost:8080/realms/keycloak-local-realm"
    network_mode: "service:localhost"
  mysqldb:
    image: mysql/mysql-server:latest
    container_name: "mysql-db"
    restart: always
    environment:
      MYSQL_DATABASE: "mysql-db"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "appuser@123"
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      retries: 10
      interval: 3s
      timeout: 30s
  postgresql:
    image: docker.io/bitnami/postgresql:latest
    container_name: postgresql
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - POSTGRESQL_USERNAME=bn_keycloak
      - POSTGRESQL_DATABASE=bitnami_keycloak
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
  keycloak:
    image: bitnami/keycloak:latest
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    volumes:
      - ./data/keycloak.default.realm.json:/opt/bitnami/keycloak/data/import/keycloak.default.realm.json
    network_mode: "service:localhost"
volumes:
  postgresql_data:
    driver: local
