server:
  port: ${port:8989}
spring:
  jpa:
    generate-ddl: false
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: none
  flyway:
    enabled: true
    baselineOnMigrate: true
    validateOnMigrate: true
    locations: classpath:db/migration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "${JWT_ISSUER_URI}"
springdoc:
  packages-to-scan: br.com.balduino.peoplepro.user.core.application.rest.controllers
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    enabled: true
